[package]
name = "philosophers-dining-problem"
version = "0.1.0"
authors = ["lykata <samuel.lindgren@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
tokio = { version = "0.2.21", features = ["full"] }
futures = "0.3.5"